### Registration
POST localhost:8080/auth/registration
Content-Type:  application/json

{ "name": "Nurbek",
  "username": "aminovnurbek007@gmail.com",
  "password": "12345"
}

### Registration Verifivation
GET http://localhost:8080/auth/registration/verification{profileId}

### Login
POST http://localhost:8080/auth/login
Content-Type:  application/json

{
  "username": "aminovnurbek007@gmail.com",
  "password": "12345"
}